name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy # Utilisation de l'environnement "deploy"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload files to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }} # Adresse de votre serveur FTP Hostinger
          username: ${{ secrets.FTP_USERNAME }} # Nom d'utilisateur FTP
          password: ${{ secrets.FTP_PASSWORD }} # Mot de passe FTP
          local-dir: ./ # Répertoire local à déployer
          server-dir: ${{ secrets.FTP_TARGET_DIR }} # Répertoire cible sur Hostinger
          exclude: |
            **/.git**
            **/.github**
