name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy # Spécifie l'environnement "deploy"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install LFTP
        run: sudo apt-get install lftp

      - name: Deploy to Hostinger via FTP
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_TARGET_DIR: ${{ secrets.FTP_TARGET_DIR }}
        run: |
          lftp -d -c "
          set ftp:passive-mode true;
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
          mirror -R ./ $FTP_TARGET_DIR --delete --verbose;
          bye
          "
